-- TechPulse AI - Optimal Consolidated Supabase Schema

-- 1. UTILITIES & FUNCTIONS
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';


-- 2. TABLE DEFINITIONS

-- Tenant Profiles
CREATE TABLE IF NOT EXISTS tenant_profiles (
    user_id             UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email               TEXT,
    full_name           TEXT,
    is_admin            BOOLEAN DEFAULT FALSE,
    role                TEXT DEFAULT 'user',
    status              TEXT DEFAULT 'active',
    slack_webhook_url   TEXT,
    discord_webhook_url TEXT,
    api_token           TEXT,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure status column exists (for backward compatibility)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'tenant_profiles' AND column_name = 'status'
  ) THEN
    ALTER TABLE tenant_profiles ADD COLUMN status TEXT DEFAULT 'active';
  END IF;
END $$;

-- Articles
CREATE TABLE IF NOT EXISTS articles (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    source_url   TEXT NOT NULL,
    title        TEXT NOT NULL,
    content      TEXT,
    summary      TEXT,
    topics       TEXT[] DEFAULT '{}',
    score        FLOAT DEFAULT 0.0,
    source       VARCHAR(100),
    is_delivered BOOLEAN DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT articles_source_url_userid_key UNIQUE (source_url, user_id)
);

-- RSS Sources
CREATE TABLE IF NOT EXISTS rss_sources (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    url        TEXT NOT NULL,
    is_active  BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT rss_sources_url_userid_key UNIQUE (url, user_id)
);

-- App Config
CREATE TABLE IF NOT EXISTS app_config (
    key        TEXT NOT NULL,
    user_id    UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    value      JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (key, user_id)
);

-- Telemetry
CREATE TABLE IF NOT EXISTS telemetry (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    service     TEXT NOT NULL,   -- 'collector', 'summarizer', 'delivery'
    metric_name TEXT,            -- Flat metric name for UI 2.0
    value       FLOAT8,          -- Flat metric value for UI 2.0
    metrics     JSONB NOT NULL,  -- Legacy JSON structure
    success     BOOLEAN DEFAULT TRUE,
    timestamp   TIMESTAMPTZ DEFAULT NOW()
);

-- Admin Audit Log
CREATE TABLE IF NOT EXISTS admin_audit_log (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_user_id  UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    action         TEXT NOT NULL,
    target_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    metadata       JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at     TIMESTAMPTZ DEFAULT NOW()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'tenant_profiles_role_check'
  ) THEN
    ALTER TABLE tenant_profiles
      ADD CONSTRAINT tenant_profiles_role_check
      CHECK (role IN ('owner', 'admin', 'operator', 'auditor', 'premium_member', 'premium', 'member', 'user'));
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'tenant_profiles_status_check'
  ) THEN
    ALTER TABLE tenant_profiles
      ADD CONSTRAINT tenant_profiles_status_check
      CHECK (status IN ('active', 'pending', 'suspended'));
  END IF;
END $$;


-- 3. INDEXES

-- Articles
CREATE INDEX IF NOT EXISTS idx_articles_user_id      ON articles(user_id);
CREATE INDEX IF NOT EXISTS idx_articles_score        ON articles(score DESC);
CREATE INDEX IF NOT EXISTS idx_articles_created_at   ON articles(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_is_delivered ON articles(is_delivered)
    WHERE is_delivered = FALSE;  -- ✅ Partial index from Original

-- RSS Sources
CREATE INDEX IF NOT EXISTS idx_rss_sources_user_id ON rss_sources(user_id);

-- Telemetry
CREATE INDEX IF NOT EXISTS idx_telemetry_user_id     ON telemetry(user_id);
CREATE INDEX IF NOT EXISTS idx_telemetry_service     ON telemetry(service);       -- ✅ From Original
CREATE INDEX IF NOT EXISTS idx_telemetry_timestamp   ON telemetry(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_telemetry_metric_name ON telemetry(metric_name);   -- ✅ From Original

-- Admin Audit Log
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_actor_user_id ON admin_audit_log(actor_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_target_user_id ON admin_audit_log(target_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_created_at ON admin_audit_log(created_at DESC);


-- 4. TRIGGERS
DROP TRIGGER IF EXISTS update_tenant_profiles_updated_at ON tenant_profiles;
CREATE TRIGGER update_tenant_profiles_updated_at
    BEFORE UPDATE ON tenant_profiles
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_rss_sources_updated_at ON rss_sources;
CREATE TRIGGER update_rss_sources_updated_at
    BEFORE UPDATE ON rss_sources
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_app_config_updated_at ON app_config;
CREATE TRIGGER update_app_config_updated_at
    BEFORE UPDATE ON app_config
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();


-- 5. ROW LEVEL SECURITY (RLS)
ALTER TABLE tenant_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_config      ENABLE ROW LEVEL SECURITY;
ALTER TABLE rss_sources     ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles        ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetry       ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_audit_log ENABLE ROW LEVEL SECURITY;

-- Tenant Profiles: granular policies ✅
DROP POLICY IF EXISTS "Users can view own profile" ON tenant_profiles;
CREATE POLICY "Users can view own profile"   ON tenant_profiles FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own profile" ON tenant_profiles;
CREATE POLICY "Users can insert own profile" ON tenant_profiles FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own profile" ON tenant_profiles;
CREATE POLICY "Users can update own profile" ON tenant_profiles FOR UPDATE USING (auth.uid() = user_id);

-- App Config: granular policies ✅
DROP POLICY IF EXISTS "Users can view own config" ON app_config;
CREATE POLICY "Users can view own config"   ON app_config FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own config" ON app_config;
CREATE POLICY "Users can insert own config" ON app_config FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own config" ON app_config;
CREATE POLICY "Users can update own config" ON app_config FOR UPDATE USING (auth.uid() = user_id);

-- RSS Sources: granular + DELETE ✅
DROP POLICY IF EXISTS "Users can view own sources" ON rss_sources;
CREATE POLICY "Users can view own sources"   ON rss_sources FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own sources" ON rss_sources;
CREATE POLICY "Users can insert own sources" ON rss_sources FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own sources" ON rss_sources;
CREATE POLICY "Users can update own sources" ON rss_sources FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own sources" ON rss_sources;
CREATE POLICY "Users can delete own sources" ON rss_sources FOR DELETE USING (auth.uid() = user_id);

-- Articles: read-only for users (pipeline uses Service Role)
DROP POLICY IF EXISTS "Users can view own articles" ON articles;
CREATE POLICY "Users can view own articles" ON articles FOR SELECT USING (auth.uid() = user_id);

-- Telemetry: read-only for users
DROP POLICY IF EXISTS "Users can view own telemetry" ON telemetry;
CREATE POLICY "Users can view own telemetry" ON telemetry FOR SELECT USING (auth.uid() = user_id);

-- Admin audit log: operators can see their own audit records only
DROP POLICY IF EXISTS "Actors can view own audit log" ON admin_audit_log;
CREATE POLICY "Actors can view own audit log"
  ON admin_audit_log
  FOR SELECT
  USING (auth.uid() = actor_user_id);


-- 6. AUTO-PROFILE TRIGGER (Self-Serve Signup)
-- Automatically create a tenant profile when a new user signs up via Supabase Auth.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.tenant_profiles (user_id, email, full_name, is_admin)
  VALUES (
    NEW.id, 
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email),
    FALSE
  );

  UPDATE public.tenant_profiles
    SET role = 'user', status = 'active'
    WHERE user_id = NEW.id;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger should only run after a new user is created in auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
