-- TechPulse AI - Optimal Consolidated Supabase Schema

-- 1. UTILITIES & FUNCTIONS
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';


-- 2. TABLE DEFINITIONS

-- Tenant Profiles
CREATE TABLE IF NOT EXISTS tenant_profiles (
    user_id             UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name           TEXT,
    is_admin            BOOLEAN DEFAULT FALSE,  -- ✅ Kept from Restoration fix
    slack_webhook_url   TEXT,
    discord_webhook_url TEXT,
    api_token           TEXT,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Articles
CREATE TABLE IF NOT EXISTS articles (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    source_url   TEXT NOT NULL,
    title        TEXT NOT NULL,
    content      TEXT,
    summary      TEXT,
    topics       TEXT[] DEFAULT '{}',
    score        FLOAT DEFAULT 0.0,
    source       VARCHAR(100),
    is_delivered BOOLEAN DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT articles_source_url_userid_key UNIQUE (source_url, user_id)
);

-- RSS Sources
CREATE TABLE IF NOT EXISTS rss_sources (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    url        TEXT NOT NULL,
    is_active  BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT rss_sources_url_userid_key UNIQUE (url, user_id)
);

-- App Config
CREATE TABLE IF NOT EXISTS app_config (
    key        TEXT NOT NULL,
    user_id    UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    value      JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (key, user_id)
);

-- Telemetry
CREATE TABLE IF NOT EXISTS telemetry (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    service     TEXT NOT NULL,   -- 'collector', 'summarizer', 'delivery'
    metric_name TEXT,            -- Flat metric name for UI 2.0
    value       FLOAT8,          -- Flat metric value for UI 2.0
    metrics     JSONB NOT NULL,  -- Legacy JSON structure
    success     BOOLEAN DEFAULT TRUE,
    timestamp   TIMESTAMPTZ DEFAULT NOW()
);


-- 3. INDEXES

-- Articles
CREATE INDEX IF NOT EXISTS idx_articles_user_id      ON articles(user_id);
CREATE INDEX IF NOT EXISTS idx_articles_score        ON articles(score DESC);
CREATE INDEX IF NOT EXISTS idx_articles_created_at   ON articles(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_is_delivered ON articles(is_delivered)
    WHERE is_delivered = FALSE;  -- ✅ Partial index from Original

-- RSS Sources
CREATE INDEX IF NOT EXISTS idx_rss_sources_user_id ON rss_sources(user_id);

-- Telemetry
CREATE INDEX IF NOT EXISTS idx_telemetry_user_id     ON telemetry(user_id);
CREATE INDEX IF NOT EXISTS idx_telemetry_service     ON telemetry(service);       -- ✅ From Original
CREATE INDEX IF NOT EXISTS idx_telemetry_timestamp   ON telemetry(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_telemetry_metric_name ON telemetry(metric_name);   -- ✅ From Original


-- 4. TRIGGERS
CREATE TRIGGER update_tenant_profiles_updated_at
    BEFORE UPDATE ON tenant_profiles
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_rss_sources_updated_at
    BEFORE UPDATE ON rss_sources
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_app_config_updated_at
    BEFORE UPDATE ON app_config
    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();


-- 5. ROW LEVEL SECURITY (RLS)
ALTER TABLE tenant_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_config      ENABLE ROW LEVEL SECURITY;
ALTER TABLE rss_sources     ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles        ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetry       ENABLE ROW LEVEL SECURITY;

-- Tenant Profiles: granular policies ✅
CREATE POLICY "Users can view own profile"   ON tenant_profiles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own profile" ON tenant_profiles FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own profile" ON tenant_profiles FOR UPDATE USING (auth.uid() = user_id);

-- App Config: granular policies ✅
CREATE POLICY "Users can view own config"   ON app_config FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own config" ON app_config FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own config" ON app_config FOR UPDATE USING (auth.uid() = user_id);

-- RSS Sources: granular + DELETE ✅
CREATE POLICY "Users can view own sources"   ON rss_sources FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own sources" ON rss_sources FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own sources" ON rss_sources FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own sources" ON rss_sources FOR DELETE USING (auth.uid() = user_id);

-- Articles: read-only for users (pipeline uses Service Role)
CREATE POLICY "Users can view own articles" ON articles FOR SELECT USING (auth.uid() = user_id);

-- Telemetry: read-only for users
CREATE POLICY "Users can view own telemetry" ON telemetry FOR SELECT USING (auth.uid() = user_id);


-- 6. AUTO-PROFILE TRIGGER (Self-Serve Signup)
-- Automatically create a tenant profile when a new user signs up via Supabase Auth.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.tenant_profiles (user_id, full_name, is_admin)
  VALUES (
    NEW.id, 
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.email),
    FALSE
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger should only run after a new user is created in auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
