// ── Permission model ───────────────────────────────────────────────────────────
export const PERMISSIONS = {
  platformAccess: 'platform.access',
  platformMetricsView: 'platform.metrics.view',
  platformTenantsView: 'platform.tenants.view',
  platformTenantsManage: 'platform.tenants.manage',
  platformRolesAssign: 'platform.roles.assign',
  platformUsersDelete: 'platform.users.delete',
  platformReportsView: 'platform.reports.view',
  workspaceDashboardView: 'workspace.dashboard.view',
  workspaceSettingsView: 'workspace.settings.view',
  workspaceSourcesView: 'workspace.sources.view',
  workspaceSourcesCreate: 'workspace.sources.create',
  workspaceSourcesUpdate: 'workspace.sources.update',
  workspaceSourcesDelete: 'workspace.sources.delete',
  workspaceSourcesBulkImport: 'workspace.sources.bulk_import',
  workspaceRulesView: 'workspace.rules.view',
  workspaceRulesManage: 'workspace.rules.manage',
  workspaceSearchUse: 'workspace.search.use',
  workspaceRadarView: 'workspace.radar.view',
  workspaceBriefView: 'workspace.brief.view',
  workspaceFeedbackSubmit: 'workspace.feedback.submit',
  workspaceWebhooksManage: 'workspace.webhooks.manage',
};

export const ROLE_PERMISSIONS = {
  owner: Object.values(PERMISSIONS),
  admin: Object.values(PERMISSIONS),
  operator: [
    PERMISSIONS.platformAccess,
    PERMISSIONS.platformMetricsView,
    PERMISSIONS.platformTenantsView,
    PERMISSIONS.platformTenantsManage,
    PERMISSIONS.platformReportsView,
  ],
  auditor: [
    PERMISSIONS.platformAccess,
    PERMISSIONS.platformMetricsView,
    PERMISSIONS.platformTenantsView,
    PERMISSIONS.platformReportsView,
  ],
  premium_member: [
    PERMISSIONS.workspaceDashboardView,
    PERMISSIONS.workspaceSettingsView,
    PERMISSIONS.workspaceSourcesView,
    PERMISSIONS.workspaceSourcesCreate,
    PERMISSIONS.workspaceSourcesUpdate,
    PERMISSIONS.workspaceSourcesDelete,
    PERMISSIONS.workspaceSourcesBulkImport,
    PERMISSIONS.workspaceRulesView,
    PERMISSIONS.workspaceRulesManage,
    PERMISSIONS.workspaceSearchUse,
    PERMISSIONS.workspaceRadarView,
    PERMISSIONS.workspaceBriefView,
    PERMISSIONS.workspaceFeedbackSubmit,
    PERMISSIONS.workspaceWebhooksManage,
  ],
  premium: [
    PERMISSIONS.workspaceDashboardView,
    PERMISSIONS.workspaceSettingsView,
    PERMISSIONS.workspaceSourcesView,
    PERMISSIONS.workspaceSourcesCreate,
    PERMISSIONS.workspaceSourcesUpdate,
    PERMISSIONS.workspaceSourcesDelete,
    PERMISSIONS.workspaceSourcesBulkImport,
    PERMISSIONS.workspaceRulesView,
    PERMISSIONS.workspaceRulesManage,
    PERMISSIONS.workspaceSearchUse,
    PERMISSIONS.workspaceRadarView,
    PERMISSIONS.workspaceBriefView,
    PERMISSIONS.workspaceFeedbackSubmit,
    PERMISSIONS.workspaceWebhooksManage,
  ],
  member: [
    PERMISSIONS.workspaceDashboardView,
    PERMISSIONS.workspaceSettingsView,
    PERMISSIONS.workspaceSourcesView,
    PERMISSIONS.workspaceSourcesCreate,
    PERMISSIONS.workspaceSourcesUpdate,
    PERMISSIONS.workspaceSourcesDelete,
    PERMISSIONS.workspaceRadarView,
    PERMISSIONS.workspaceBriefView,
    PERMISSIONS.workspaceFeedbackSubmit,
  ],
  user: [
    PERMISSIONS.workspaceDashboardView,
    PERMISSIONS.workspaceSettingsView,
    PERMISSIONS.workspaceSourcesView,
    PERMISSIONS.workspaceSourcesCreate,
    PERMISSIONS.workspaceSourcesUpdate,
    PERMISSIONS.workspaceSourcesDelete,
    PERMISSIONS.workspaceRadarView,
    PERMISSIONS.workspaceBriefView,
    PERMISSIONS.workspaceFeedbackSubmit,
  ],
};

// Feature aliases preserve the existing component API while delegating to permissions.
export const FEATURE_PERMISSIONS = {
  semanticSearch: [PERMISSIONS.workspaceSearchUse],
  webhookDelivery: [PERMISSIONS.workspaceWebhooksManage],
  bulkImport: [PERMISSIONS.workspaceSourcesBulkImport],
  inferenceRules: [PERMISSIONS.workspaceRulesManage],
  adminConsole: [PERMISSIONS.platformAccess],
  assignRoles: [PERMISSIONS.platformRolesAssign],
  deleteUsers: [PERMISSIONS.platformUsersDelete],
  articleFeedback: [PERMISSIONS.workspaceFeedbackSubmit],
};

export const NAV_PERMISSIONS = {
  dashboard: [PERMISSIONS.platformAccess, PERMISSIONS.workspaceDashboardView],
  settings: [PERMISSIONS.workspaceSettingsView],
  morningBrief: [PERMISSIONS.platformReportsView, PERMISSIONS.workspaceBriefView],
  semanticSearch: [PERMISSIONS.workspaceSearchUse],
  radar: [PERMISSIONS.workspaceRadarView],
  adminConsole: [PERMISSIONS.platformAccess],
};

// RSS source limits per role
export const RSS_LIMITS = {
  admin:   Infinity,
  owner:   Infinity,
  operator: 0,
  auditor: 0,         // auditors cannot add sources
  premium_member: 50,
  premium: 50,
  member:  5,
  user:    5,
};
